# Generated by Django 4.1.1 on 2022-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
