# Generated by Django 4.1.1 on 2022-09-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendomapp', '0003_alter_users_avatar_alter_users_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='socil_insurance_number',
            new_name='social_insurance_number',
        ),
    ]
