# Generated by Django 4.1.1 on 2022-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendomapp', '0004_rename_socil_insurance_number_users_social_insurance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
